export default {
	OBJECT_GAS_OCCUPATION_ROAD_REGISTRATION_BASIC: "挖掘占道登记基本信息",

	OBJECT_GAS_BIG_BUILDING: "大型行业综合体",

	OBJECT_GAS_OCCUPATION_ROAD_REGISTRATION: "挖掘占道登记",

	OBJECT_FIRE_CONTROL_HIGHT_BUILDING: "高层建筑",

	OBJECT_FIRE_CONTROL_KEY_UNIT: "消防重点单位",

	OBJECT_TRAFFIC_VEHICLE_TRANSPORT: "运输车辆",

	OBJECT_MAIN_MONITOR_AREA: "重点监测区域",

	OBJECT_MAIN_FAST_ROAD: "重点快速路",

	OBJECT_TRAFFIC_GUEST_CRISIS: "涉两客一危企业",

	OBJECT_TRAFFIC_PASSENGER_STATION: "客运站",

	OBJECT_WATER_SUPPLY_NETWORK: "供水线网",

	OBJECT_WATER_SUPPLY_PIPE_POINT: "供水管点",

	OBJECT_MONITORING_POINT_MUNICIPAL: "消火栓监测点位",

	OBJECT_WATER_SUPPLY_FIRE_WATER_MONITOR: "水鹤监测点位",

	OBJECT_HEATING_NETWORK_PIPE: "管线信息",

	OBJECT_HEATING_NETWORK_EXCHANGE_STATION: "换热站",

	OBJECT_HEATING_NETWORK_HEAT_FACTORY: "热源厂",

	OBJECT_HEATING_NETWORK_ENTERPRISE: "供热企业",

	EQUIPMENT_BUILD_TOWER_CRANE: "塔吊",

	EQUIPMENT_BUILDING_VIDEO: "监测摄像头",

	EQUIPMENT_BUILDING_GAS_MONITORING: "气体监测",

	EQUIPMENT_ARCH_CROWN_SETTLEMENT: "支护结构拱顶沉降监测",

	EQUIPMENT_CLEARANCE_CONVERGENCE_MONITORING: "支护结构净空收敛监测",

	OBJECT_BRIDGE_BASE: "桥梁",

	OBJECT_SUBWAY_SAFETY_TUNNEL: "隧道",

	CORRIDOR_ENVIRONMENT: "廊内环境",

	UTILITY_TUNNEL: "综合管廊",

	OBJECT_SUBWAY_SAFETY_TRANSFER_STATION: "地铁站",

	OBJECT_SUBWAY_SAFETY_FLOOD_CONTROL_POINT: "防汛点位",

	OBJECT_SUBWAY_SAFETY_SUBWAY_PASSAGE: "通道",

	KEY_TOURIST_ATTRACTIONS: "重点旅游景区",

	OBJECT_MONITORING_ELEVATOR: "电梯",

	OBJECT_ASSEMBLY_OCCUPANCIES_LIBRARY: "图书馆",

	OBJECT_ASSEMBLY_OCCUPANCIES_CULTURE: "文化馆",

	LARGE_COMMERICAL_COMPLEX: "大型商业综合体",

	OBJECT_NATURAL_DISASTER_CONTACT: "各区县（市）森林防灭火工作联络表",

	OBJECT_NATURAL_DISASTER_COMMAND: "森林防灭火指挥部成员单位",

	OBJECT_NATURAL_DISASTER_FOREST_FIRECONTROL_GOODS: "森林消防物资",

	OBJECT_NATURAL_DISASTER_FOREST_FIRECONTROL_PROFESSIONAL: "森林消防专家",

	OBJECT_NATURAL_DISASTER_FOREST_CHECK_STATION: "检查站",

	OBJECT_FOREST_FIRE_KEY_AREA: "森林防火重点区域",

	OBJECT_FOREST_FIRE_FOREST_LOOK_FIRE: "火情瞭望点",

	OBJECT_NATURAL_DISASTER_FOREST_FORESTER: "护林员信息",

	OBJECT_NATURAL_DISASTER_FOREST_FARM: "林场",

	OBJECT_WATER_DRAINAGE_RAINWATER_PUMP: "雨水泵站",

	OBJECT_WATER_DRAINAGE_THRESHOLD: "排水设备监测阈值",

	OBJECT_WATER_DRAINAGE_RESERVOIR: "水库",

	OBJECT_WATER_DRAINAGE_RIVER_COURSE: "河道",

	OBJECT_WATER_DRAINAGE_RAINWATER_PIPE: "雨水管网",

	OBJECT_WATER_DRAINAGE_TUBEWELL: "管井",

	OBJECT_WATER_DRAINAGE_SEWAGE_PIPE: "污水管网",

	OBJECT_WATER_DRAINAGE_MIXED_PIPE_NETWORK: "混接管网",

	OBJECT_WATER_DRAINAGE_OUTLET: "入河排水口",

	OBJECT_WATER_DRAINAGE_WATERLOGGING_POINT: "易涝点",

	OBJECT_WATER_DRAINAGE_SEWAGE_LIFT: "污水泵站",

	OBJECT_NATURAL_DISASTER_SUBSIDE: "塌陷区域",

	OBJECT_NATURAL_DISASTER_DANGER_POINT: "地质灾害隐患点",

	OBJECT_NATURAL_DISASTER_COUNTRY_WEATHER_STATION: "国家气象站",

	OBJECT_NATURAL_DISASTER_SNOW_STATION: "降雪观测站",

	OBJECT_NATURAL_DISASTER_EARTHQUAKE_STATION: "地震台站点",

	OBJECT_NATURAL_DISASTER_OBSERVE_STATION: "地震宏观测报站 ",

	OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE: "企业",

	OBJECT_HAZARDOUS_CHEMICALS_STORAGE_TANK: "储罐",

	OBJECT_HAZARDOUS_CHEMICALS_GAS_UNITS: "气体监测装置",

	OBJECT_HAZARDOUS_CHEMICALS_PROCESS_UNITS: "生产装置",

	OBJECT_HAZARDOUS_CHEMICALS_TANK_FIELD: "罐区",

	FACILITY_BUILDING_PROJECT_ENGINEERING: "项目工程",

	FACILITY_UNDERGROUND_FOR_SUBWAY: "地铁暗挖工程",

	SYYJ_FACILITY_GAS_PLACE: "用气场所",

	SYYJ_FACILITY_GAS_PIPELINE: "燃气管线",

	SYYJ_FACILITY_GAS_DENSELY_POPULATED: "人员密集区",

	SYYJ_FACILITY_GAS_CONFERENCE_HOTEL: "主要会议宾馆",

	SYYJ_FACILITY_GAS_KEY_UNIT: "重点单位",

	SYYJ_FACILITY_GAS_ADJACENT_SPACE: "地下相邻空间",

	SYYJ_FACILITY_GAS_REGULATOR_STATION: "调压站",

	SYYJ_FACILITY_GAS_COMMERCIAL_SYNTHESES: "大型商业综合体",

	SYYJ_FACILITY_GAS_STATIONS: "设施加油站",
};
