let obj = {
    "assessmentUnitType": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
    "resultId": "1752946205427167234",
    "regionName": "大东区",
    "latitude": "41.786342",
    "updateUser": "1123598821738675201",
    "gradeCodeName": "一般风险(深黄)",
    "updateTime": "2024-02-01 14:47:31",
    "levelName": "一般风险",
    "objName": "中国航空油料有限责任公司沈阳分公司",
    "resultindexList": [],
    "cmdbType": {
        "modifyDate": "2024-01-12 09:27:55",
        "name": "企业（重大危险源企业、非煤矿山企业、工贸企业、危化品企业）",
        "id": 35989,
        "right": "U",
        "config": {
            "IsLayer": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "right": "D",
                "value": "true",
                "key": "IsLayer"
            },
            "ViewShowTree": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "right": "U",
                "value": "true",
                "key": "ViewShowTree"
            }
        },
        "key": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
        "labels": [
            "MONITOR_OBJECT",
            "SYYJ_RESOURCE",
            "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
        ],
        "createDate": "2022-11-03 11:45:32",
        "attrs": {
            "NumberProtectedTargets": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "周边防护目标数量",
                "key": "NumberProtectedTargets",
                "desc": "周边防护目标数量",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "ItemStatus": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Oneline_status",
                "search": false,
                "name": "企业状态",
                "key": "ItemStatus",
                "desc": "企业状态",
                "order": 1059,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "SafetyContactPhone": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "安全人联系电话",
                "key": "SafetyContactPhone",
                "desc": "安全人联系电话",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "CompanyId": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "企业ID",
                "key": "CompanyId",
                "desc": "公司ID",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "Address": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "企业地址",
                "key": "Address",
                "desc": "企业地址",
                "order": 1052,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "Township": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "所属街道",
                "key": "Township",
                "desc": "所属街道",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "OrderNumber": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DOUBLE",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "序号",
                "key": "OrderNumber",
                "desc": "",
                "order": 1,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "JoinstStatus": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Joinst_status",
                "search": false,
                "name": "接入状态",
                "key": "JoinstStatus",
                "desc": "接入状态",
                "order": 1057,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "SafetyContact": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "安全联系人",
                "key": "SafetyContact",
                "desc": "安全联系人",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "ManageLevel": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Manage_level",
                "search": false,
                "name": "管理级别",
                "key": "ManageLevel",
                "desc": "管理级别",
                "order": 1428,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "IndustryType": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Industry_type",
                "search": false,
                "name": "行业类型",
                "key": "IndustryType",
                "desc": "行业类型",
                "order": 1056,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "HazardNature": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazard_nature",
                "search": false,
                "name": "危险源性质",
                "key": "HazardNature",
                "desc": "危险源性质",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "NumberHazards": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "D",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "周边危险源数量",
                "key": "NumberHazards",
                "desc": "周边危险源数量",
                "order": 0,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "Coordinate": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "MAP_POINT",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "经纬度",
                "key": "Coordinate",
                "desc": "经纬度",
                "order": 1190,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "ItemName": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": true,
                "valueDataType": "STRING",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "企业名称",
                "key": "ItemName",
                "desc": "企业名称",
                "order": 1051,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "OnelineStatus": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": true,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Oneline_status",
                "search": false,
                "name": "在线状态",
                "key": "OnelineStatus",
                "desc": "在线状态",
                "order": 1058,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "Region": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "monitor_alarm_area",
                "search": false,
                "name": "所属区域",
                "key": "Region",
                "desc": "所属区域",
                "order": 1189,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "FirmWheelMan": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "企业负责人",
                "key": "FirmWheelMan",
                "desc": "企业负责人",
                "order": 1053,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "LinkType": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "STRING",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "",
                "search": false,
                "name": "联系方式",
                "key": "LinkType",
                "desc": "联系方式",
                "order": 1054,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            },
            "RiskType": {
                "typeKey": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
                "defaultValue": "",
                "show": true,
                "require": false,
                "valueDataType": "DROPDOWN",
                "right": "U",
                "dataSyncModify": false,
                "kpiCode": "",
                "valueReg": "hazardous_chemicals_ohce_Risk_type",
                "search": false,
                "name": "风险级别",
                "key": "RiskType",
                "desc": "风险级别",
                "order": 1055,
                "group": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
            }
        }
    },
    "score": "78.8248",
    "cmdbItem": {
        "modifyDate": "2024-01-12 15:06:19",
        "typeName": "",
        "id": 37265,
        "type": "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE",
        "moid": "276ad2399c09ba8b8373b9ebe6346201",
        "labels": [
            "MONITOR_OBJECT",
            "ci",
            "SYYJ_RESOURCE",
            "OBJECT_HAZARDOUS_CHEMICALS_ENTERPRISE"
        ],
        "createDate": "2022-11-08 16:38:22",
        "attrs": {
            "NumberProtectedTargets": "64",
            "ItemStatus": "",
            "SafetyContactPhone": "13904036509",
            "CompanyId": "1189007765733978375",
            "Address": "大东区小河沿路3号航空城中国航油东北公司",
            "Township": "大东区长安街道",
            "JoinstStatus": "1",
            "OrderNumber": "9",
            "SafetyContact": "张海峰",
            "ManageLevel": "1",
            "IndustryType": "1",
            "NumberHazards": "0",
            "Coordinate": "POINT(123.492868 41.786342)",
            "ItemName": "中国航空油料有限责任公司沈阳分公司",
            "OnelineStatus": "1",
            "Region": "2101",
            "LinkType": "13909824385",
            "FirmWheelMan": "张知诚",
            "RiskType": "4"
        }
    },
    "createDept": "1560481063061426178",
    "isDeleted": 0,
    "createTime": "2024-02-01 14:45:18",
    "objId": "276ad2399c09ba8b8373b9ebe6346201",
    "createUser": "1123598821738675201",
    "id": "1752946206182141953",
    "gradeCode": "deepk_yellow",
    "region": "210104",
    "status": 1,
    "longitude": "123.492868"
}